-- 由 parity/gen_ddl.py 从 sakuramediabe 的 Peewee 模型自动生成。
-- 不要手工编辑：改上游模型后重新运行本脚本。
-- 权威来源 = github.com/tinypinglite/sakuramediabe 的 src/model/
--
-- 主键是 4 字节自增（integer），不是 bigint：Peewee 的 AutoField 继承
-- IntegerField，AUTO 在 PostgreSQL 上落 INTEGER。Rust 侧对应 i32。
--
-- timestamp 不带 time zone，与上游 naive datetime 约定一致。
--
-- 外键统一在建表之后用 ALTER TABLE 追加，因为自引用外键
-- （actor.merged_into_id -> actor）使拓扑排序无解。

CREATE TABLE IF NOT EXISTS actor (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  javdb_id varchar(64) NOT NULL UNIQUE,
  name text NOT NULL,
  alias_name text NOT NULL DEFAULT '',
  merged_into_id integer NULL,
  profile_image_id integer NULL,
  profile_image_override_id integer NULL,
  display_name_override varchar(255) NULL,
  javdb_type integer NOT NULL DEFAULT 0,
  gender integer NOT NULL DEFAULT 0,
  is_subscribed boolean NOT NULL DEFAULT false,
  subscribed_at timestamp NULL,
  subscribed_movies_synced_at timestamp NULL,
  subscribed_movies_full_synced_at timestamp NULL,
  birthday date NULL,
  height_cm integer NULL,
  bust_cm integer NULL,
  waist_cm integer NULL,
  hips_cm integer NULL,
  cup varchar(255) NULL,
  birthplace varchar(255) NULL,
  blood_type varchar(255) NULL,
  field_owners jsonb NOT NULL DEFAULT '{}'::jsonb,
  mutation_revision bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS background_task_run (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  task_key varchar(64) NOT NULL,
  task_name varchar(255) NOT NULL,
  trigger_type varchar(32) NOT NULL,
  mutex_key varchar(128) NULL,
  state varchar(32) NOT NULL DEFAULT 'pending',
  progress_current integer NULL,
  progress_total integer NULL,
  progress_text varchar(255) NULL,
  result_summary text NOT NULL,
  result_text text NULL,
  error_message text NULL,
  started_at timestamp NULL,
  finished_at timestamp NULL,
  params text NULL,
  scheduled_at timestamp NULL,
  lease_expires_at timestamp NULL
);

CREATE TABLE IF NOT EXISTS clip_collection (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  name varchar(255) NOT NULL UNIQUE,
  description text NOT NULL DEFAULT '',
  owner_plugin_id varchar(64) NULL,
  plugin_key varchar(128) NULL
);

CREATE TABLE IF NOT EXISTS clip_collection_item (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  collection_id integer NOT NULL,
  clip_id integer NOT NULL,
  position integer NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_recommendation_item (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  snapshot_date date NOT NULL,
  movie_id integer NOT NULL UNIQUE,
  rank integer NOT NULL UNIQUE,
  score double precision NOT NULL DEFAULT 0.0,
  reason_codes text NOT NULL,
  reason_texts text NOT NULL,
  signal_scores text NOT NULL,
  generated_at timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS download_client (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  name varchar(255) NOT NULL UNIQUE,
  provider_config text NOT NULL,
  library_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS download_resource_blacklist (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  info_hash varchar(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS download_submission_record (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  client_id integer NOT NULL,
  task_id integer NULL,
  movie_number varchar(255) NOT NULL,
  indexer_name varchar(255) NOT NULL,
  title varchar(255) NOT NULL,
  source_uri text NOT NULL,
  info_hash varchar(40) NOT NULL,
  state varchar(32) NOT NULL DEFAULT 'submitting',
  remote_id varchar(255) NULL,
  error_code varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS download_task (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  client_id integer NOT NULL,
  movie_number varchar(255) NULL,
  remote_id varchar(255) NOT NULL,
  name varchar(255) NOT NULL,
  state varchar(32) NOT NULL DEFAULT 'queued',
  progress double precision NOT NULL DEFAULT 0,
  completed_source_ref text NULL,
  import_status varchar(32) NOT NULL DEFAULT 'pending',
  import_task_run_id integer NULL
);

CREATE TABLE IF NOT EXISTS image (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  origin varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS image_search_index_state (
  id integer NOT NULL DEFAULT 1,
  indexed_space_id varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS image_search_session (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  session_id varchar(64) NOT NULL UNIQUE,
  status varchar(32) NOT NULL DEFAULT 'ready',
  page_size integer NOT NULL DEFAULT 20,
  next_cursor text NULL,
  query_vector text NULL,
  movie_ids text NULL,
  exclude_movie_ids text NULL,
  score_threshold double precision NULL,
  expires_at timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS indexer (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  name varchar(255) NOT NULL UNIQUE,
  url varchar(1024) NOT NULL,
  kind varchar(32) NOT NULL,
  api_key varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS indexer_download_client (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  indexer_id integer NOT NULL,
  download_client_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS media (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  movie_number varchar(255) NULL,
  video_item_id integer NULL,
  library_id integer NOT NULL,
  storage_ref text NOT NULL,
  file_name varchar(1024) NOT NULL DEFAULT '',
  resolution varchar(32) NULL,
  file_size_bytes bigint NOT NULL DEFAULT 0,
  file_hash varchar(64) NULL,
  import_source_identity varchar(512) NULL,
  duration_seconds integer NOT NULL DEFAULT 0,
  video_info text NULL,
  valid boolean NOT NULL DEFAULT true,
  thumbnail_generation_state varchar(32) NOT NULL,
  thumbnail_attempt_count integer NOT NULL DEFAULT 0,
  thumbnail_deferred_count integer NOT NULL DEFAULT 0,
  thumbnail_next_retry_at timestamp NULL,
  thumbnail_last_error_code varchar(64) NULL,
  thumbnail_last_error text NULL,
  thumbnail_terminal_at timestamp NULL
);

CREATE TABLE IF NOT EXISTS media_clip (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  media_id integer NULL,
  movie_number varchar(64) NULL,
  start_offset_seconds integer NOT NULL,
  end_offset_seconds integer NOT NULL,
  title varchar(255) NOT NULL DEFAULT '',
  file_path varchar(1024) NOT NULL,
  file_size_bytes bigint NOT NULL DEFAULT 0,
  duration_seconds integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS media_library (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  name varchar(255) NOT NULL UNIQUE,
  provider_key varchar(255) NOT NULL,
  provider_config text NOT NULL,
  account_key varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS media_point (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  media_id integer NULL,
  thumbnail_id integer NULL,
  image_id integer NOT NULL,
  movie_number varchar(64) NULL,
  video_item_id integer NULL,
  offset_seconds integer NOT NULL
);

CREATE TABLE IF NOT EXISTS media_progress (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  media_id integer NOT NULL,
  position_seconds integer NOT NULL DEFAULT 0,
  last_watched_at timestamp NULL
);

CREATE TABLE IF NOT EXISTS media_thumbnail (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  media_id integer NOT NULL,
  image_id integer NOT NULL,
  offset integer NOT NULL,
  image_search_index_status integer NOT NULL
);

CREATE TABLE IF NOT EXISTS moment_collection (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  name varchar(255) NOT NULL UNIQUE,
  description text NOT NULL DEFAULT '',
  owner_plugin_id varchar(64) NULL,
  plugin_key varchar(128) NULL
);

CREATE TABLE IF NOT EXISTS moment_collection_item (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  collection_id integer NOT NULL,
  point_id integer NOT NULL,
  position integer NOT NULL
);

CREATE TABLE IF NOT EXISTS moment_recommendation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  rank integer NOT NULL UNIQUE,
  score double precision NOT NULL DEFAULT 0.0,
  strategy varchar(32) NOT NULL,
  reason varchar(255) NOT NULL,
  movie_id integer NOT NULL,
  media_id integer NOT NULL,
  thumbnail_id integer NOT NULL UNIQUE,
  offset_seconds integer NOT NULL,
  seed_point_id integer NULL,
  seed_thumbnail_id integer NULL,
  source_movie_id integer NULL,
  visual_score double precision NULL,
  movie_similarity_score double precision NULL,
  generated_at timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS movie (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  javdb_id varchar(64) NULL UNIQUE,
  metadata_source jsonb NULL,
  javdb_next_check_at timestamp NULL,
  movie_number varchar(255) NOT NULL UNIQUE,
  title text NOT NULL,
  release_date timestamp NULL,
  duration_minutes integer NOT NULL DEFAULT 0,
  score double precision NOT NULL DEFAULT 0,
  score_number integer NOT NULL DEFAULT 0,
  watched_count integer NOT NULL DEFAULT 0,
  cover_image_id integer NULL,
  thin_cover_image_id integer NULL,
  summary text NOT NULL DEFAULT '',
  series_id integer NULL,
  maker_name varchar(255) NULL,
  director_name varchar(255) NULL,
  want_watch_count integer NOT NULL DEFAULT 0,
  comment_count integer NOT NULL DEFAULT 0,
  interaction_synced_at timestamp NULL,
  heat integer NOT NULL DEFAULT 0,
  is_collection boolean NOT NULL DEFAULT false,
  is_subscribed boolean NOT NULL DEFAULT false,
  is_blacklisted boolean NOT NULL DEFAULT false,
  subscribed_at timestamp NULL,
  subscription_search_state varchar(32) NOT NULL DEFAULT 'pending',
  subscription_search_attempt_count integer NOT NULL DEFAULT 0,
  subscription_search_retry_round integer NOT NULL DEFAULT 0,
  subscription_search_last_attempted_at timestamp NULL,
  subscription_search_last_succeeded_at timestamp NULL,
  subscription_search_next_retry_at timestamp NULL,
  subscription_search_error_code varchar(64) NULL,
  subscription_search_last_error text NULL,
  subscription_search_last_error_at timestamp NULL,
  field_owners jsonb NOT NULL DEFAULT '{}'::jsonb,
  mutation_revision bigint NOT NULL DEFAULT 0,
  CONSTRAINT movie_subscription_blacklist_exclusive CHECK (NOT (is_subscribed AND is_blacklisted))
);

CREATE TABLE IF NOT EXISTS movie_actor (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id integer NOT NULL,
  actor_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS movie_plot_image (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id integer NOT NULL,
  image_id integer NOT NULL,
  image_search_index_status integer NOT NULL
);

CREATE TABLE IF NOT EXISTS movie_series (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS movie_tag (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id integer NOT NULL,
  tag_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS playlist (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  kind varchar(64) NOT NULL,
  name varchar(255) NOT NULL UNIQUE,
  description text NOT NULL DEFAULT '',
  owner_plugin_id varchar(64) NULL,
  plugin_key varchar(128) NULL
);

CREATE TABLE IF NOT EXISTS playlist_movie (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  playlist_id integer NOT NULL,
  movie_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS ranking_item (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  source_key varchar(64) NOT NULL,
  board_key varchar(64) NOT NULL,
  period varchar(32) NOT NULL DEFAULT '',
  rank integer NOT NULL,
  movie_number varchar(255) NOT NULL,
  movie_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS schema_migration (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL UNIQUE,
  applied_at timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS subtitle (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  movie_id integer NOT NULL,
  file_path varchar(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS system_notification (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  category varchar(32) NOT NULL,
  title varchar(255) NOT NULL,
  content text NOT NULL,
  event_type varchar(64) NULL,
  dedupe_key varchar(255) NULL UNIQUE,
  resource_type varchar(64) NULL,
  resource_id integer NULL,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp NULL,
  related_task_run_id integer NULL,
  related_resource_type varchar(64) NULL,
  related_resource_id integer NULL
);

CREATE TABLE IF NOT EXISTS tag (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  name varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_refresh_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  token_id text NOT NULL UNIQUE,
  token_hash text NOT NULL,
  status varchar(32) NOT NULL,
  expires_at timestamp NOT NULL,
  revoked_at timestamp NULL,
  replaced_by_token_id text NULL,
  client_ip text NULL,
  user_agent text NULL
);

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  last_login_at timestamp NULL
);

CREATE TABLE IF NOT EXISTS video_collection (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  name varchar(255) NOT NULL UNIQUE,
  description text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS video_collection_item (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  collection_id integer NOT NULL,
  video_item_id integer NOT NULL,
  position integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS video_item (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NULL,
  updated_at timestamp NULL,
  title varchar(255) NOT NULL,
  summary text NOT NULL DEFAULT '',
  cover_image_id integer NULL,
  release_date timestamp NULL,
  extra text NULL
);

-- 外键

ALTER TABLE actor ADD CONSTRAINT actor_merged_into_id_fk FOREIGN KEY (merged_into_id) REFERENCES actor (merged_into_id) ON DELETE SET NULL;
ALTER TABLE actor ADD CONSTRAINT actor_profile_image_id_fk FOREIGN KEY (profile_image_id) REFERENCES image (profile_image_id) ON DELETE SET NULL;
ALTER TABLE actor ADD CONSTRAINT actor_profile_image_override_id_fk FOREIGN KEY (profile_image_override_id) REFERENCES image (profile_image_override_id) ON DELETE SET NULL;
ALTER TABLE clip_collection_item ADD CONSTRAINT clip_collection_item_collection_id_fk FOREIGN KEY (collection_id) REFERENCES clip_collection (collection_id) ON DELETE CASCADE;
ALTER TABLE clip_collection_item ADD CONSTRAINT clip_collection_item_clip_id_fk FOREIGN KEY (clip_id) REFERENCES media_clip (clip_id) ON DELETE CASCADE;
ALTER TABLE daily_recommendation_item ADD CONSTRAINT daily_recommendation_item_movie_id_fk FOREIGN KEY (movie_id) REFERENCES movie (movie_id) ON DELETE CASCADE;
ALTER TABLE download_client ADD CONSTRAINT download_client_library_id_fk FOREIGN KEY (library_id) REFERENCES media_library (library_id) ON DELETE CASCADE;
ALTER TABLE download_task ADD CONSTRAINT download_task_client_id_fk FOREIGN KEY (client_id) REFERENCES download_client (client_id) ON DELETE CASCADE;
ALTER TABLE download_task ADD CONSTRAINT download_task_import_task_run_id_fk FOREIGN KEY (import_task_run_id) REFERENCES background_task_run (import_task_run_id) ON DELETE SET NULL;
ALTER TABLE indexer_download_client ADD CONSTRAINT indexer_download_client_indexer_id_fk FOREIGN KEY (indexer_id) REFERENCES indexer (indexer_id) ON DELETE CASCADE;
ALTER TABLE indexer_download_client ADD CONSTRAINT indexer_download_client_download_client_id_fk FOREIGN KEY (download_client_id) REFERENCES download_client (download_client_id) ON DELETE CASCADE;
ALTER TABLE media ADD CONSTRAINT media_movie_number_fk FOREIGN KEY (movie_number) REFERENCES movie (movie_number) ON DELETE CASCADE;
ALTER TABLE media ADD CONSTRAINT media_video_item_id_fk FOREIGN KEY (video_item_id) REFERENCES video_item (video_item_id) ON DELETE CASCADE;
ALTER TABLE media ADD CONSTRAINT media_library_id_fk FOREIGN KEY (library_id) REFERENCES media_library (library_id) ON DELETE CASCADE;
ALTER TABLE media_clip ADD CONSTRAINT media_clip_media_id_fk FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE SET NULL;
ALTER TABLE media_point ADD CONSTRAINT media_point_media_id_fk FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE SET NULL;
ALTER TABLE media_point ADD CONSTRAINT media_point_thumbnail_id_fk FOREIGN KEY (thumbnail_id) REFERENCES media_thumbnail (thumbnail_id) ON DELETE SET NULL;
ALTER TABLE media_point ADD CONSTRAINT media_point_image_id_fk FOREIGN KEY (image_id) REFERENCES image (image_id) ON DELETE RESTRICT;
ALTER TABLE media_progress ADD CONSTRAINT media_progress_media_id_fk FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE;
ALTER TABLE media_thumbnail ADD CONSTRAINT media_thumbnail_media_id_fk FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE;
ALTER TABLE media_thumbnail ADD CONSTRAINT media_thumbnail_image_id_fk FOREIGN KEY (image_id) REFERENCES image (image_id) ON DELETE CASCADE;
ALTER TABLE moment_collection_item ADD CONSTRAINT moment_collection_item_collection_id_fk FOREIGN KEY (collection_id) REFERENCES moment_collection (collection_id) ON DELETE CASCADE;
ALTER TABLE moment_collection_item ADD CONSTRAINT moment_collection_item_point_id_fk FOREIGN KEY (point_id) REFERENCES media_point (point_id) ON DELETE CASCADE;
ALTER TABLE moment_recommendation ADD CONSTRAINT moment_recommendation_movie_id_fk FOREIGN KEY (movie_id) REFERENCES movie (movie_id) ON DELETE CASCADE;
ALTER TABLE moment_recommendation ADD CONSTRAINT moment_recommendation_media_id_fk FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE;
ALTER TABLE moment_recommendation ADD CONSTRAINT moment_recommendation_thumbnail_id_fk FOREIGN KEY (thumbnail_id) REFERENCES media_thumbnail (thumbnail_id) ON DELETE CASCADE;
ALTER TABLE moment_recommendation ADD CONSTRAINT moment_recommendation_seed_point_id_fk FOREIGN KEY (seed_point_id) REFERENCES media_point (seed_point_id) ON DELETE SET NULL;
ALTER TABLE moment_recommendation ADD CONSTRAINT moment_recommendation_seed_thumbnail_id_fk FOREIGN KEY (seed_thumbnail_id) REFERENCES media_thumbnail (seed_thumbnail_id) ON DELETE SET NULL;
ALTER TABLE moment_recommendation ADD CONSTRAINT moment_recommendation_source_movie_id_fk FOREIGN KEY (source_movie_id) REFERENCES movie (source_movie_id) ON DELETE SET NULL;
ALTER TABLE movie ADD CONSTRAINT movie_cover_image_id_fk FOREIGN KEY (cover_image_id) REFERENCES image (cover_image_id) ON DELETE SET NULL;
ALTER TABLE movie ADD CONSTRAINT movie_thin_cover_image_id_fk FOREIGN KEY (thin_cover_image_id) REFERENCES image (thin_cover_image_id) ON DELETE SET NULL;
ALTER TABLE movie ADD CONSTRAINT movie_series_id_fk FOREIGN KEY (series_id) REFERENCES movie_series (series_id) ON DELETE SET NULL;
ALTER TABLE movie_actor ADD CONSTRAINT movie_actor_movie_id_fk FOREIGN KEY (movie_id) REFERENCES movie (movie_id) ON DELETE CASCADE;
ALTER TABLE movie_actor ADD CONSTRAINT movie_actor_actor_id_fk FOREIGN KEY (actor_id) REFERENCES actor (actor_id) ON DELETE CASCADE;
ALTER TABLE movie_plot_image ADD CONSTRAINT movie_plot_image_movie_id_fk FOREIGN KEY (movie_id) REFERENCES movie (movie_id) ON DELETE CASCADE;
ALTER TABLE movie_plot_image ADD CONSTRAINT movie_plot_image_image_id_fk FOREIGN KEY (image_id) REFERENCES image (image_id) ON DELETE CASCADE;
ALTER TABLE movie_tag ADD CONSTRAINT movie_tag_movie_id_fk FOREIGN KEY (movie_id) REFERENCES movie (movie_id) ON DELETE CASCADE;
ALTER TABLE movie_tag ADD CONSTRAINT movie_tag_tag_id_fk FOREIGN KEY (tag_id) REFERENCES tag (tag_id) ON DELETE CASCADE;
ALTER TABLE playlist_movie ADD CONSTRAINT playlist_movie_playlist_id_fk FOREIGN KEY (playlist_id) REFERENCES playlist (playlist_id) ON DELETE CASCADE;
ALTER TABLE playlist_movie ADD CONSTRAINT playlist_movie_movie_id_fk FOREIGN KEY (movie_id) REFERENCES movie (movie_id) ON DELETE CASCADE;
ALTER TABLE ranking_item ADD CONSTRAINT ranking_item_movie_id_fk FOREIGN KEY (movie_id) REFERENCES movie (movie_id) ON DELETE CASCADE;
ALTER TABLE subtitle ADD CONSTRAINT subtitle_movie_id_fk FOREIGN KEY (movie_id) REFERENCES movie (movie_id) ON DELETE CASCADE;
ALTER TABLE system_notification ADD CONSTRAINT system_notification_related_task_run_id_fk FOREIGN KEY (related_task_run_id) REFERENCES background_task_run (related_task_run_id) ON DELETE SET NULL;
ALTER TABLE video_collection_item ADD CONSTRAINT video_collection_item_collection_id_fk FOREIGN KEY (collection_id) REFERENCES video_collection (collection_id) ON DELETE CASCADE;
ALTER TABLE video_collection_item ADD CONSTRAINT video_collection_item_video_item_id_fk FOREIGN KEY (video_item_id) REFERENCES video_item (video_item_id) ON DELETE CASCADE;
ALTER TABLE video_item ADD CONSTRAINT video_item_cover_image_id_fk FOREIGN KEY (cover_image_id) REFERENCES image (cover_image_id) ON DELETE SET NULL;

-- 索引

CREATE INDEX IF NOT EXISTS actor_javdb_id_idx ON actor (javdb_id);
CREATE INDEX IF NOT EXISTS actor_name_idx ON actor (name);
CREATE INDEX IF NOT EXISTS actor_merged_into_id_idx ON actor (merged_into_id);
CREATE INDEX IF NOT EXISTS actor_is_subscribed_idx ON actor (is_subscribed);
CREATE INDEX IF NOT EXISTS actor_subscribed_at_idx ON actor (subscribed_at);
CREATE INDEX IF NOT EXISTS actor_subscribed_movies_synced_at_idx ON actor (subscribed_movies_synced_at);
CREATE INDEX IF NOT EXISTS actor_subscribed_movies_full_synced_at_idx ON actor (subscribed_movies_full_synced_at);
CREATE INDEX IF NOT EXISTS background_task_run_task_key_created_at_idx ON background_task_run (task_key, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS background_task_run_mutex_key_uniq ON background_task_run (mutex_key);
CREATE INDEX IF NOT EXISTS background_task_run_state_scheduled_at_idx ON background_task_run (state, scheduled_at);
CREATE INDEX IF NOT EXISTS background_task_run_task_key_idx ON background_task_run (task_key);
CREATE INDEX IF NOT EXISTS background_task_run_trigger_type_idx ON background_task_run (trigger_type);
CREATE INDEX IF NOT EXISTS background_task_run_state_idx ON background_task_run (state);
CREATE UNIQUE INDEX IF NOT EXISTS clip_collection_owner_plugin_id_plugin_key_uniq ON clip_collection (owner_plugin_id, plugin_key);
CREATE UNIQUE INDEX IF NOT EXISTS clip_collection_item_collection_id_clip_id_uniq ON clip_collection_item (collection_id, clip_id);
CREATE INDEX IF NOT EXISTS clip_collection_item_position_idx ON clip_collection_item (position);
CREATE INDEX IF NOT EXISTS daily_recommendation_item_snapshot_date_idx ON daily_recommendation_item (snapshot_date);
CREATE INDEX IF NOT EXISTS daily_recommendation_item_generated_at_idx ON daily_recommendation_item (generated_at);
CREATE INDEX IF NOT EXISTS download_client_name_idx ON download_client (name);
CREATE INDEX IF NOT EXISTS download_submission_record_task_id_idx ON download_submission_record (task_id);
CREATE UNIQUE INDEX IF NOT EXISTS download_task_client_id_remote_id_uniq ON download_task (client_id, remote_id);
CREATE INDEX IF NOT EXISTS download_task_movie_number_idx ON download_task (movie_number);
CREATE INDEX IF NOT EXISTS download_task_state_idx ON download_task (state);
CREATE INDEX IF NOT EXISTS download_task_import_status_idx ON download_task (import_status);
CREATE INDEX IF NOT EXISTS image_origin_pattern ON image (origin text_pattern_ops);
CREATE INDEX IF NOT EXISTS image_search_session_session_id_idx ON image_search_session (session_id);
CREATE INDEX IF NOT EXISTS image_search_session_expires_at_idx ON image_search_session (expires_at);
CREATE INDEX IF NOT EXISTS indexer_name_idx ON indexer (name);
CREATE UNIQUE INDEX IF NOT EXISTS indexer_download_client_indexer_id_download_client_id_uniq ON indexer_download_client (indexer_id, download_client_id);
CREATE INDEX IF NOT EXISTS media_thumbnail_generation_state_thumbnail_next_retry_at_idx ON media (thumbnail_generation_state, thumbnail_next_retry_at);
CREATE INDEX IF NOT EXISTS media_library_id_import_source_identity_idx ON media (library_id, import_source_identity);
CREATE INDEX IF NOT EXISTS media_file_hash_idx ON media (file_hash);
CREATE UNIQUE INDEX IF NOT EXISTS media_clip_media_id_start_offset_seconds_end_offset_seconds_uniq ON media_clip (media_id, start_offset_seconds, end_offset_seconds);
CREATE INDEX IF NOT EXISTS media_clip_movie_number_idx ON media_clip (movie_number);
CREATE INDEX IF NOT EXISTS media_clip_start_offset_seconds_idx ON media_clip (start_offset_seconds);
CREATE INDEX IF NOT EXISTS media_clip_end_offset_seconds_idx ON media_clip (end_offset_seconds);
CREATE INDEX IF NOT EXISTS media_library_name_idx ON media_library (name);
CREATE INDEX IF NOT EXISTS media_library_provider_key_idx ON media_library (provider_key);
CREATE INDEX IF NOT EXISTS media_point_offset_seconds_idx ON media_point (offset_seconds);
CREATE UNIQUE INDEX IF NOT EXISTS media_progress_media_id_uniq ON media_progress (media_id);
CREATE UNIQUE INDEX IF NOT EXISTS media_thumbnail_media_id_offset_uniq ON media_thumbnail (media_id, offset);
CREATE INDEX IF NOT EXISTS media_thumbnail_image_search_index_status_id_idx ON media_thumbnail (image_search_index_status, id);
CREATE INDEX IF NOT EXISTS media_thumbnail_offset_idx ON media_thumbnail (offset);
CREATE UNIQUE INDEX IF NOT EXISTS moment_collection_owner_plugin_id_plugin_key_uniq ON moment_collection (owner_plugin_id, plugin_key);
CREATE UNIQUE INDEX IF NOT EXISTS moment_collection_item_collection_id_point_id_uniq ON moment_collection_item (collection_id, point_id);
CREATE INDEX IF NOT EXISTS moment_collection_item_position_idx ON moment_collection_item (position);
CREATE INDEX IF NOT EXISTS moment_recommendation_strategy_idx ON moment_recommendation (strategy);
CREATE INDEX IF NOT EXISTS moment_recommendation_offset_seconds_idx ON moment_recommendation (offset_seconds);
CREATE INDEX IF NOT EXISTS moment_recommendation_generated_at_idx ON moment_recommendation (generated_at);
CREATE INDEX IF NOT EXISTS movie_movie_number_upper ON movie (upper(movie_number));
CREATE INDEX IF NOT EXISTS movie_release_date_sort ON movie (release_date DESC NULLS LAST, id DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS movie_subscribed_at_sort ON movie (subscribed_at DESC NULLS LAST, id DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS movie_javdb_id_idx ON movie (javdb_id);
CREATE INDEX IF NOT EXISTS movie_javdb_next_check_at_idx ON movie (javdb_next_check_at);
CREATE INDEX IF NOT EXISTS movie_movie_number_idx ON movie (movie_number);
CREATE INDEX IF NOT EXISTS movie_release_date_idx ON movie (release_date);
CREATE INDEX IF NOT EXISTS movie_duration_minutes_idx ON movie (duration_minutes);
CREATE INDEX IF NOT EXISTS movie_score_idx ON movie (score);
CREATE INDEX IF NOT EXISTS movie_interaction_synced_at_idx ON movie (interaction_synced_at);
CREATE INDEX IF NOT EXISTS movie_is_collection_idx ON movie (is_collection);
CREATE INDEX IF NOT EXISTS movie_is_subscribed_idx ON movie (is_subscribed);
CREATE INDEX IF NOT EXISTS movie_is_blacklisted_idx ON movie (is_blacklisted);
CREATE INDEX IF NOT EXISTS movie_subscribed_at_idx ON movie (subscribed_at);
CREATE INDEX IF NOT EXISTS movie_subscription_search_state_idx ON movie (subscription_search_state);
CREATE UNIQUE INDEX IF NOT EXISTS movie_actor_movie_id_actor_id_uniq ON movie_actor (movie_id, actor_id);
CREATE UNIQUE INDEX IF NOT EXISTS movie_plot_image_movie_id_image_id_uniq ON movie_plot_image (movie_id, image_id);
CREATE INDEX IF NOT EXISTS movie_plot_image_image_search_index_status_id_idx ON movie_plot_image (image_search_index_status, id);
CREATE INDEX IF NOT EXISTS movie_series_name_idx ON movie_series (name);
CREATE UNIQUE INDEX IF NOT EXISTS movie_tag_movie_id_tag_id_uniq ON movie_tag (movie_id, tag_id);
CREATE UNIQUE INDEX IF NOT EXISTS playlist_owner_plugin_id_plugin_key_uniq ON playlist (owner_plugin_id, plugin_key);
CREATE INDEX IF NOT EXISTS playlist_kind_idx ON playlist (kind);
CREATE UNIQUE INDEX IF NOT EXISTS playlist_movie_playlist_id_movie_id_uniq ON playlist_movie (playlist_id, movie_id);
CREATE UNIQUE INDEX IF NOT EXISTS ranking_item_source_key_board_key_period_rank_uniq ON ranking_item (source_key, board_key, period, rank);
CREATE INDEX IF NOT EXISTS ranking_item_source_key_board_key_period_idx ON ranking_item (source_key, board_key, period);
CREATE INDEX IF NOT EXISTS ranking_item_source_key_idx ON ranking_item (source_key);
CREATE INDEX IF NOT EXISTS ranking_item_board_key_idx ON ranking_item (board_key);
CREATE INDEX IF NOT EXISTS ranking_item_period_idx ON ranking_item (period);
CREATE INDEX IF NOT EXISTS ranking_item_rank_idx ON ranking_item (rank);
CREATE INDEX IF NOT EXISTS ranking_item_movie_number_idx ON ranking_item (movie_number);
CREATE INDEX IF NOT EXISTS schema_migration_name_idx ON schema_migration (name);
CREATE UNIQUE INDEX IF NOT EXISTS subtitle_movie_id_file_path_uniq ON subtitle (movie_id, file_path);
CREATE INDEX IF NOT EXISTS system_notification_category_idx ON system_notification (category);
CREATE INDEX IF NOT EXISTS system_notification_is_read_idx ON system_notification (is_read);
CREATE INDEX IF NOT EXISTS tag_name_idx ON tag (name);
CREATE INDEX IF NOT EXISTS user_refresh_tokens_token_id_idx ON user_refresh_tokens (token_id);
CREATE INDEX IF NOT EXISTS users_username_idx ON users (username);
CREATE INDEX IF NOT EXISTS video_collection_name_idx ON video_collection (name);
CREATE UNIQUE INDEX IF NOT EXISTS video_collection_item_collection_id_video_item_id_uniq ON video_collection_item (collection_id, video_item_id);
CREATE INDEX IF NOT EXISTS video_collection_item_position_idx ON video_collection_item (position);
CREATE INDEX IF NOT EXISTS video_item_title_idx ON video_item (title);
CREATE INDEX IF NOT EXISTS video_item_release_date_idx ON video_item (release_date);
