#!/usr/bin/env python3
"""从 schema 契约生成 PostgreSQL DDL。

契约来自 schema_contract.py（用 ast 解析 Peewee 模型），本脚本只做翻译，
不重新解析模型 —— 两套解析器必然漂移，而漂移会表现为「DDL 少了一列」。

覆盖：列类型与长度、可空性、Python 侧默认值、服务端 DEFAULT、主键与唯一约束、
字段级索引、复合索引（Meta.indexes）、外键引用与 ON DELETE 动作、
CHECK 约束（Meta.constraints 原样透传）、
函数/排序/修饰符索引（模块级 add_index）。

主键类型：Peewee 的 `class AutoField(IntegerField)`，AUTO 在 PostgreSQL 上落
INTEGER，所以隐式 id 是 4 字节自增列，与 Rust 侧 i32 对应。两处必须一起改，
否则 int4 会在读取时静默 widening 成 i64。

用法：
    python gen_ddl.py                 # 打印 DDL
    python gen_ddl.py --out schema.sql # 写文件
    python gen_ddl.py --tables        # 只打印建表顺序
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from schema_contract import collect  # noqa: E402

# 契约类型 -> PostgreSQL 列类型。
#
# timestamp 不带 time zone：上游全是 naive datetime，列类型是
# `timestamp without time zone`。用 timestamptz 会改变解码语义。
COLUMN_TYPES = {
    "text": "text",
    "text/json": "text",
    "jsonb": "jsonb",
    "int4": "integer",
    "int8": "bigint",
    "float8": "double precision",
    "numeric": "numeric",
    "bool": "boolean",
    "timestamp": "timestamp",
    "date": "date",
    "time": "time",
    "uuid": "uuid",
}


def render_default(value, ctype):
    if ctype == "bool":
        return "true" if value else "false"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, dict):
        return "''{}''" if not value else "'[]'"
    if isinstance(value, list):
        return "'[]'"
    if isinstance(value, str):
        return "'%s'" % value.replace("'", "''")
    return "NULL"


def column_ddl(col):
    """渲染单列的 DDL 片段。"""
    # 是否外键要在替换 ctype **之前**记下来：ctype 会被改成目标列的类型，
    # 之后再判断 `ctype == "fk"` 就永远为假，长度会取错来源。
    is_fk = col["type"] == "fk"
    if is_fk:
        # 外键的列类型等于它所引用的那一列。绝大多数是 int4（指向 id），
        # 但 `Media.movie_number` 指向 `Movie.movie_number`（varchar 255），
        # 一律当 int4 会让建表直接失败。
        ctype = col.get("ref_column_type") or "int4"
    else:
        ctype = col["type"]
    base = COLUMN_TYPES.get(ctype)
    if base is None:
        raise ValueError("unmapped column type: %r" % col["type"])

    # CharField(max_length=N) -> varchar(N)；TextField 与无 max_length 的 -> text
    max_len = col.get("ref_column_max_length") if is_fk else col.get("max_length")
    if ctype == "text" and max_len:
        base = "varchar(%d)" % max_len

    parts = [col["name"], base]
    if col.get("auto_increment"):
        parts.append("GENERATED BY DEFAULT AS IDENTITY")
    if col.get("primary_key"):
        parts.append("PRIMARY KEY")
    if not col.get("primary_key"):
        parts.append("NULL" if col.get("nullable") else "NOT NULL")
    if col.get("unique") and not col.get("primary_key"):
        parts.append("UNIQUE")

    # 服务端默认值优先：constraints=[SQL("DEFAULT ...")] 进 DDL，
    # 而 Peewee kwargs 里的 default= 只影响 peewee 自己的写路径。
    if col.get("server_default"):
        parts.append(col["server_default"])
    elif col.get("default") is not None:
        parts.append("DEFAULT %s" % render_default(col["default"], ctype))
    return " ".join(parts)


def index_name(table, cols, unique=False):
    return "%s_%s_%s" % (table, "_".join(cols), "uniq" if unique else "idx")


def create_table(model):
    """建表。**不含外键** —— 外键由 separate_fk_ddl() 在建表后统一追加。"""
    table = model["table"]
    body = []
    for col in model["columns"].values():
        body.append("  " + column_ddl(col))
    for check in model.get("check_constraints", []):
        body.append("  " + check)
    return "CREATE TABLE IF NOT EXISTS %s (\n%s\n);" % (table, ",\n".join(body))


def create_indexes(model):
    """复合索引、模块级索引、字段级单列索引。"""
    table = model["table"]
    out = []
    for cols, unique in model.get("indexes", []):
        kind = "UNIQUE INDEX" if unique else "INDEX"
        out.append(
            "CREATE %s IF NOT EXISTS %s ON %s (%s);"
            % (kind, index_name(table, cols, unique), table, ", ".join(cols))
        )
    for entry in model.get("module_indexes", []):
        out.append(
            "CREATE INDEX IF NOT EXISTS %s ON %s (%s);"
            % (entry["name"], table, ", ".join(entry["expressions"]))
        )
    for col in model["columns"].values():
        if col.get("index") and not col.get("primary_key"):
            out.append(
                "CREATE INDEX IF NOT EXISTS %s ON %s (%s);"
                % (index_name(table, [col["name"]]), table, col["name"])
            )
    return out


def topological_order(models):
    """按外键依赖排序建表顺序。

    自引用外键（`Actor.merged_into_id -> actor`）会形成长度为 1 的环，
    深度优先在这种环上必然无限递归。这里先把所有表按字典序排好、建表
    并**不**内联外键，外键统一在建表之后用 ALTER TABLE 追加 —— 这样环与
    非环的情况走同一条代码路径，不需要分支，也不会漏约束。

    返回按字母序的模型列表；外键由 separate_fk_ddl() 单独输出。
    """
    return sorted(models, key=lambda m: m["table"])


def separate_fk_ddl(models):
    """外键约束单独成段。

    自引用外键（`actor.merged_into_id -> actor`）让「目标表先建」的拓扑排序
    无解 —— 深度优先在长度为 1 的环上必然无限递归。所以外键不在 CREATE TABLE
    里内联，而是在建表之后统一 ALTER TABLE 追加。环与非环走同一条路径，
    少一个分支也就少一个漏约束的机会。
    """
    out = []
    for model in sorted(models, key=lambda m: m["table"]):
        table = model["table"]
        for col in model["columns"].values():
            if col["type"] != "fk" or not col.get("ref_table"):
                continue
            action = col.get("on_delete") or "NO ACTION"
            target_col = col.get("ref_field") or col["name"]
            out.append(
                "ALTER TABLE %s ADD CONSTRAINT %s_%s_fk "
                "FOREIGN KEY (%s) REFERENCES %s (%s) ON DELETE %s;"
                % (
                    table,
                    table,
                    col["name"],
                    col["name"],
                    col["ref_table"],
                    target_col,
                    action,
                )
            )
    return out


HEADER = """-- 由 parity/gen_ddl.py 从 sakuramediabe 的 Peewee 模型自动生成。
-- 不要手工编辑：改上游模型后重新运行本脚本。
-- 权威来源 = github.com/tinypinglite/sakuramediabe 的 src/model/
--
-- 主键是 4 字节自增（integer），不是 bigint：Peewee 的 AutoField 继承
-- IntegerField，AUTO 在 PostgreSQL 上落 INTEGER。Rust 侧对应 i32。
--
-- timestamp 不带 time zone，与上游 naive datetime 约定一致。
--
-- 外键统一在建表之后用 ALTER TABLE 追加，因为自引用外键
-- （actor.merged_into_id -> actor）使拓扑排序无解。
"""


def generate(models):
    """返回 (DDL 文本, 建表顺序的模型列表)。"""
    ordered = topological_order(models)
    chunks = [HEADER]
    for model in ordered:
        chunks.append(create_table(model) + "\n")
    chunks.append("-- 外键\n")
    chunks.append("\n".join(separate_fk_ddl(models)) + "\n")
    chunks.append("-- 索引\n")
    idx = []
    for model in ordered:
        idx.extend(create_indexes(model))
    chunks.append("\n".join(idx) + "\n")
    return "\n".join(chunks), ordered


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", help="写到该路径而不是 stdout")
    ap.add_argument("--tables", action="store_true", help="只打印建表顺序")
    args = ap.parse_args()

    models = collect()

    if args.tables:
        for i, m in enumerate(topological_order(models), 1):
            print("  %2d. %s" % (i, m["table"]))
        return 0

    ddl, ordered = generate(models)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(ddl)
        print(
            "wrote %s (%d tables, %d bytes)" % (args.out, len(ordered), len(ddl))
        )
    else:
        print(ddl)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
